[package]
name = "qfetch-cli"
description = "A blazing fast, highly configurable and lightweight fetch tool written in Rust."
license = "GPL-3.0-or-later"
repository = "https://codeberg.org/quixaq/qfetch"
readme = "README.md"
keywords = ["cli", "fetch", "system", "linux", "system-info"]
categories = ["command-line-utilities"]
version = "0.3.1"
edition = "2024"

[[bin]]
name = "qfetch"
path = "src/main.rs"

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))'.dependencies]
raw-cpuid = "11.6.0"

[dependencies]
console = "0.16.2"
getgpuname = "0.1.4"
gethostname = "1.1.0"
humansize = { version = "2.1.3", features = ["no_alloc" ] }
nix = { version = "0.31.3", features = [ "fs", "feature" ] }
terminal_size = "0.4.4"

[build-dependencies]
cargo-build = "1.0.0"
color-backtrace = "0.7.4"
console = "0.16.2"
serde = { version = "1.0.228", features = [ "derive" ]}
serde_yaml = "0.9.34"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
