modules:
  general:
    - id: title
      enabled: true
      key: ""
    - id: os
      enabled: true
      key: OS
    - id: host
      enabled: true
      key: Host
    - id: kernel
      enabled: true
      key: Kernel
    - id: uptime
      enabled: true
      key: Uptime
    - id: shell
      enabled: true
      key: Shell
    - id: de
      enabled: true
      key: DE
    - id: theme
      enabled: true
      key: Theme
    - id: cursor
      enabled: true
      key: Cursor
    - id: cpu
      enabled: true
      key: CPU
    - id: gpu
      enabled: true
      key: GPU
    - id: ram
      enabled: true
      key: Memory
    - id: swap
      enabled: true
      key: Swap
    - id: mounts
      enabled: true
      key: Disk
    - id: locale
      enabled: true
      key: Locale
    - id: standard_palette
      enabled: true
      key: ""
    - id: bright_palette
      enabled: true
      key: ""
module_settings:
  title:
    separator_char: "-"
  ram:
    thresholds:
      medium: 30
      high: 80
  swap:
    thresholds:
      medium: 15
      high: 40
  mounts:
    thresholds:
      # low is always 0
      medium: 20
      high: 80
colors:
  title: "#b19cd9"
  title_sep: "a37"
  keys: "#b19cd9"
  separator: "#ff6961"
  values: "#eec1cb"
  mountpoints: "#eec1cb"
  low: "a92"
  medium: "a93"
  high: "a91"
logo:
  enabled: true
  padding:
    left: 1
    right: 4
    char: " "
    replace_spaces_with_char: false
  include: # the first logo on the list will be used as fallback
    - id: nixos
      colors:
        - "#967ce2"
        - "#8951c1"
